reformat

diff --git a/apt-cyg b/apt-cyg
--- a/apt-cyg
+++ b/apt-cyg
@@ -23,10 +23,9 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 # THE SOFTWARE.
 
-if [ ${BASH_VERSINFO}${BASH_VERSINFO[1]} -lt 42 ]
-then
-  echo 'Bash version 4.2+ required'
-  exit
+if [ ${BASH_VERSINFO}${BASH_VERSINFO[1]} -lt 42 ] ; then
+    echo 'Bash version 4.2+ required'
+    exit
 fi
 
 usage="\
@@ -119,21 +118,21 @@ Copyright (c) 2005-9 Stephen Jungels
 "
 
 function wget {
-  if command wget -h &>/dev/null
-  then
-    command wget "$@"
-  else
-    warn wget is not installed, using lynx as fallback
-    set "${*: -1}"
-    lynx -source "$1" > "${1##*/}"
-  fi
+    if command wget -h &>/dev/null
+    then
+        command wget "$@"
+    else
+        warn wget is not installed, using lynx as fallback
+        set "${*: -1}"
+        lynx -source "$1" > "${1##*/}"
+    fi
 }
 
 function find-workspace {
-  # default working directory and mirror
-  
-  # work wherever setup worked last, if possible
-  cache=$(awk '
+    # default working directory and mirror
+    
+    # work wherever setup worked last, if possible
+    cache=$(awk '
   BEGIN {
     RS = "\n\\<"
     FS = "\n\t"
@@ -143,70 +142,70 @@ function find-workspace {
   }
   ' /etc/setup/setup.rc)
 
-  mirror=$(awk '
+    mirror=$(awk '
   /last-mirror/ {
     getline
     print $1
   }
   ' /etc/setup/setup.rc)
-  mirrordir=$(sed '
+    mirrordir=$(sed '
   s / %2f g
   s : %3a g
   ' <<< "$mirror")
 
-  mkdir -p "$cache/$mirrordir/$arch"
-  cd "$cache/$mirrordir/$arch"
-  if [ -e setup.ini ]
-  then
-    return 0
-  else
-    get-setup
-    return 1
-  fi
+    mkdir -p "$cache/$mirrordir/$arch"
+    cd "$cache/$mirrordir/$arch"
+    if [ -e setup.ini ]
+    then
+        return 0
+    else
+        get-setup
+        return 1
+    fi
 }
 
 function get-setup {
-  touch setup.ini
-  mv setup.ini setup.ini-save
-  wget -N $mirror/$arch/setup.bz2
-  if [ -e setup.bz2 ]
-  then
-    bunzip2 setup.bz2
-    mv setup setup.ini
-    echo Updated setup.ini
-  else
-    echo Error updating setup.ini, reverting
-    mv setup.ini-save setup.ini
-  fi
+    touch setup.ini
+    mv setup.ini setup.ini-save
+    wget -N $mirror/$arch/setup.bz2
+    if [ -e setup.bz2 ]
+    then
+        bunzip2 setup.bz2
+        mv setup setup.ini
+        echo Updated setup.ini
+    else
+        echo Error updating setup.ini, reverting
+        mv setup.ini-save setup.ini
+    fi
 }
 
 function check-packages {
-  if [[ $pks ]]
-  then
-    return 0
-  else
-    echo No packages found.
-    return 1
-  fi
+    if [[ $pks ]]
+    then
+        return 0
+    else
+        echo No packages found.
+        return 1
+    fi
 }
 
 function warn {
-  printf '\e[1;31m%s\e[m\n' "$*" >&2
+    printf '\e[1;31m%s\e[m\n' "$*" >&2
 }
 
 function apt-update {
-  if find-workspace
-  then
-    get-setup
-  fi
+    if find-workspace
+    then
+        get-setup
+    fi
 }
 
 function apt-category {
-  check-packages
-  find-workspace
-  for pkg in "${pks[@]}"
-  do
-    awk '
+    check-packages
+    find-workspace
+    for pkg in "${pks[@]}"
+    do
+        awk '
     $1 == "@" {
       pck = $2
     }
@@ -214,53 +213,53 @@ function apt-category {
       print pck
     }
     ' query="$pks" setup.ini
-  done
+    done
 }
 
 function apt-list {
-  local sbq
-  for pkg in "${pks[@]}"
-  do
-    let sbq++ && echo
-    awk 'NR>1 && $1~pkg && $0=$1' pkg="$pkg" /etc/setup/installed.db
-  done
-  let sbq && return
-  awk 'NR>1 && $0=$1' /etc/setup/installed.db
+    local sbq
+    for pkg in "${pks[@]}"
+    do
+        let sbq++ && echo
+        awk 'NR>1 && $1~pkg && $0=$1' pkg="$pkg" /etc/setup/installed.db
+    done
+    let sbq && return
+    awk 'NR>1 && $0=$1' /etc/setup/installed.db
 }
 
 function apt-listall {
-  check-packages
-  find-workspace
-  local sbq
-  for pkg in "${pks[@]}"
-  do
-    let sbq++ && echo
-    awk '$1~pkg && $0=$1' RS='\n\n@ ' FS='\n' pkg="$pkg" setup.ini
-  done
+    check-packages
+    find-workspace
+    local sbq
+    for pkg in "${pks[@]}"
+    do
+        let sbq++ && echo
+        awk '$1~pkg && $0=$1' RS='\n\n@ ' FS='\n' pkg="$pkg" setup.ini
+    done
 }
 
 function apt-listfiles {
-  check-packages
-  find-workspace
-  local pkg sbq
-  for pkg in "${pks[@]}"
-  do
-    (( sbq++ )) && echo
-    if [ ! -e /etc/setup/"$pkg".lst.gz ]
-    then
-      download "$pkg"
-    fi
-    gzip -cd /etc/setup/"$pkg".lst.gz
-  done
+    check-packages
+    find-workspace
+    local pkg sbq
+    for pkg in "${pks[@]}"
+    do
+        (( sbq++ )) && echo
+        if [ ! -e /etc/setup/"$pkg".lst.gz ]
+        then
+            download "$pkg"
+        fi
+        gzip -cd /etc/setup/"$pkg".lst.gz
+    done
 }
 
 function apt-show {
-  find-workspace
-  check-packages
-  for pkg in "${pks[@]}"
-  do
-    (( notfirst++ )) && echo
-    awk '
+    find-workspace
+    check-packages
+    for pkg in "${pks[@]}"
+    do
+        (( notfirst++ )) && echo
+        awk '
     $1 == query {
       print
       fd++
@@ -270,15 +269,15 @@ function apt-show {
         print "Unable to locate package " query
     }
     ' RS='\n\n@ ' FS='\n' query="$pkg" setup.ini
-  done
+    done
 }
 
 function apt-depends {
-  find-workspace
-  check-packages
-  for pkg in "${pks[@]}"
-  do
-    awk '
+    find-workspace
+    check-packages
+    for pkg in "${pks[@]}"
+    do
+        awk '
     @include "join"
     $1 == "@" {
       apg = $2
@@ -305,14 +304,14 @@ function apt-depends {
       delete spath[length(spath)]
     }
     ' setup.ini
-  done
+    done
 }
 
 function apt-rdepends {
-  find-workspace
-  for pkg in "${pks[@]}"
-  do
-    awk '
+    find-workspace
+    for pkg in "${pks[@]}"
+    do
+        awk '
     @include "join"
     $1 == "@" {
       apg = $2
@@ -339,126 +338,126 @@ function apt-rdepends {
       delete spath[length(spath)]
     }
     ' setup.ini
-  done
+    done
 }
 
 function apt-download {
-  check-packages
-  find-workspace
-  local pkg sbq
-  for pkg in "${pks[@]}"
-  do
-    (( sbq++ )) && echo
-    download "$pkg"
-  done
+    check-packages
+    find-workspace
+    local pkg sbq
+    for pkg in "${pks[@]}"
+    do
+        (( sbq++ )) && echo
+        download "$pkg"
+    done
 }
 
 function download {
-  local pkg digest digactual
-  pkg=$1
-  # look for package and save desc file
+    local pkg digest digactual
+    pkg=$1
+    # look for package and save desc file
 
-  awk '$1 == pc' RS='\n\n@ ' FS='\n' pc=$pkg setup.ini > desc
-  if [ ! -s desc ]
-  then
-    echo Unable to locate package $pkg
-    exit 1
-  fi
+    awk '$1 == pc' RS='\n\n@ ' FS='\n' pc=$pkg setup.ini > desc
+    if [ ! -s desc ]
+    then
+        echo Unable to locate package $pkg
+        exit 1
+    fi
 
-  # download and unpack the bz2 or xz file
+    # download and unpack the bz2 or xz file
 
-  # pick the latest version, which comes first
-  set -- $(awk '$1 == "install:"' desc)
-  if (( ! $# ))
-  then
-    echo 'Could not find "install" in package description: obsolete package?'
-    exit 1
-  fi
+    # pick the latest version, which comes first
+    set -- $(awk '$1 == "install:"' desc)
+    if (( ! $# ))
+    then
+        echo 'Could not find "install" in package description: obsolete package?'
+        exit 1
+    fi
 
-  dn=$(dirname $2)
-  bn=$(basename $2)
+    dn=$(dirname $2)
+    bn=$(basename $2)
 
-  # check the md5
-  digest=$4
-  case ${#digest} in
-   32) hash=md5sum    ;;
-  128) hash=sha512sum ;;
-  esac
-  mkdir -p "$cache/$mirrordir/$dn"
-  cd "$cache/$mirrordir/$dn"
-  if ! test -e $bn || ! $hash -c <<< "$digest $bn"
-  then
-    wget -O $bn $mirror/$dn/$bn
-    $hash -c <<< "$digest $bn" || exit
-  fi
+    # check the md5
+    digest=$4
+    case ${#digest} in
+        32) hash=md5sum    ;;
+        128) hash=sha512sum ;;
+    esac
+    mkdir -p "$cache/$mirrordir/$dn"
+    cd "$cache/$mirrordir/$dn"
+    if ! test -e $bn || ! $hash -c <<< "$digest $bn"
+    then
+        wget -O $bn $mirror/$dn/$bn
+        $hash -c <<< "$digest $bn" || exit
+    fi
 
-  tar tf $bn | gzip > /etc/setup/"$pkg".lst.gz
-  cd ~-
-  mv desc "$cache/$mirrordir/$dn"
-  echo $dn $bn > /tmp/dwn
+    tar tf $bn | gzip > /etc/setup/"$pkg".lst.gz
+    cd ~-
+    mv desc "$cache/$mirrordir/$dn"
+    echo $dn $bn > /tmp/dwn
 }
 
 function apt-search {
-  check-packages
-  echo Searching downloaded packages...
-  for pkg in "${pks[@]}"
-  do
-    key=$(type -P "$pkg" | sed s./..)
-    [[ $key ]] || key=$pkg
-    for manifest in /etc/setup/*.lst.gz
+    check-packages
+    echo Searching downloaded packages...
+    for pkg in "${pks[@]}"
     do
-      if gzip -cd $manifest | grep -q "$key"
-      then
-        package=$(sed '
+        key=$(type -P "$pkg" | sed s./..)
+        [[ $key ]] || key=$pkg
+        for manifest in /etc/setup/*.lst.gz
+        do
+            if gzip -cd $manifest | grep -q "$key"
+            then
+                package=$(sed '
         s,/etc/setup/,,
         s,.lst.gz,,
         ' <<< $manifest)
-        echo $package
-      fi
+                echo $package
+            fi
+        done
     done
-  done
 }
 
 function apt-searchall {
-  cd /tmp
-  for pkg in "${pks[@]}"
-  do
-    printf -v qs 'text=1&arch=%s&grep=%s' $arch "$pkg"
-    wget -O matches cygwin.com/cgi-bin2/package-grep.cgi?"$qs"
-    awk '
+    cd /tmp
+    for pkg in "${pks[@]}"
+    do
+        printf -v qs 'text=1&arch=%s&grep=%s' $arch "$pkg"
+        wget -O matches cygwin.com/cgi-bin2/package-grep.cgi?"$qs"
+        awk '
     NR == 1 {next}
     mc[$1]++ {next}
     /-debuginfo-/ {next}
     /^cygwin32-/ {next}
     {print $1}
     ' FS=-[[:digit:]] matches
-  done
+    done
 }
 
 function apt-install {
-  check-packages
-  find-workspace
-  local pkg dn bn requires wr package sbq script
-  for pkg in "${pks[@]}"
-  do
+    check-packages
+    find-workspace
+    local pkg dn bn requires wr package sbq script
+    for pkg in "${pks[@]}"
+    do
 
-  if grep -q "^$pkg " /etc/setup/installed.db
-  then
-    echo Package $pkg is already installed, skipping
-    continue
-  fi
-  (( sbq++ )) && echo
-  echo Installing $pkg
+        if grep -q "^$pkg " /etc/setup/installed.db
+        then
+            echo Package $pkg is already installed, skipping
+            continue
+        fi
+        (( sbq++ )) && echo
+        echo Installing $pkg
 
-  download $pkg
-  read dn bn </tmp/dwn
-  echo Unpacking...
+        download $pkg
+        read dn bn </tmp/dwn
+        echo Unpacking...
 
-  cd "$cache/$mirrordir/$dn"
-  tar -x -C / -f $bn
-  # update the package database
+        cd "$cache/$mirrordir/$dn"
+        tar -x -C / -f $bn
+        # update the package database
 
-  awk '
+        awk '
   ins != 1 && pkg < $1 {
     print pkg, bz, 0
     ins = 1
@@ -468,68 +467,68 @@ function apt-install {
     if (ins != 1) print pkg, bz, 0
   }
   ' pkg="$pkg" bz=$bn /etc/setup/installed.db > /tmp/awk.$$
-  mv /etc/setup/installed.db /etc/setup/installed.db-save
-  mv /tmp/awk.$$ /etc/setup/installed.db
+        mv /etc/setup/installed.db /etc/setup/installed.db-save
+        mv /tmp/awk.$$ /etc/setup/installed.db
 
-  [ -v nodeps ] && continue
-  # recursively install required packages
+        [ -v nodeps ] && continue
+        # recursively install required packages
 
-  requires=$(awk '$1=="requires", $0=$2' FS=': ' desc)
-  cd ~-
-  wr=0
-  if [[ $requires ]]
-  then
-    echo Package $pkg requires the following packages, installing:
-    echo $requires
-    for package in $requires
-    do
-      if grep -q "^$package " /etc/setup/installed.db
-      then
-        echo Package $package is already installed, skipping
-        continue
-      fi
-      apt-cyg install --noscripts $package || (( wr++ ))
+        requires=$(awk '$1=="requires", $0=$2' FS=': ' desc)
+        cd ~-
+        wr=0
+        if [[ $requires ]]
+        then
+            echo Package $pkg requires the following packages, installing:
+            echo $requires
+            for package in $requires
+            do
+                if grep -q "^$package " /etc/setup/installed.db
+                then
+                    echo Package $package is already installed, skipping
+                    continue
+                fi
+                apt-cyg install --noscripts $package || (( wr++ ))
+            done
+        fi
+        if (( wr ))
+        then
+            echo some required packages did not install, continuing
+        fi
+
+        # run all postinstall scripts
+
+        [ -v noscripts ] && continue
+        find /etc/postinstall -name '*.sh' | while read script
+        do
+            echo Running $script
+            $script
+            mv $script $script.done
+        done
+        echo Package $pkg installed
+
     done
-  fi
-  if (( wr ))
-  then
-    echo some required packages did not install, continuing
-  fi
-
-  # run all postinstall scripts
-
-  [ -v noscripts ] && continue
-  find /etc/postinstall -name '*.sh' | while read script
-  do
-    echo Running $script
-    $script
-    mv $script $script.done
-  done
-  echo Package $pkg installed
-
-  done
 }
 
 function apt-remove {
-  check-packages
-  cd /etc
-  cygcheck awk bash bunzip2 grep gzip mv sed tar xz > setup/essential.lst
-  for pkg in "${pks[@]}"
-  do
+    check-packages
+    cd /etc
+    cygcheck awk bash bunzip2 grep gzip mv sed tar xz > setup/essential.lst
+    for pkg in "${pks[@]}"
+    do
 
-  if ! grep -q "^$pkg " setup/installed.db
-  then
-    echo Package $pkg is not installed, skipping
-    continue
-  fi
+        if ! grep -q "^$pkg " setup/installed.db
+        then
+            echo Package $pkg is not installed, skipping
+            continue
+        fi
 
-  if [ ! -e setup/"$pkg".lst.gz ]
-  then
-    warn Package manifest missing, cannot remove $pkg. Exiting
-    exit 1
-  fi
-  gzip -dk setup/"$pkg".lst.gz
-  awk '
+        if [ ! -e setup/"$pkg".lst.gz ]
+        then
+            warn Package manifest missing, cannot remove $pkg. Exiting
+            exit 1
+        fi
+        gzip -dk setup/"$pkg".lst.gz
+        awk '
   NR == FNR {
     if ($NF) ess[$NF]
     next
@@ -538,136 +537,134 @@ function apt-remove {
     exit 1
   }
   ' FS='[/\\\\]' setup/{essential,$pkg}.lst
-  esn=$?
-  if [ $esn = 0 ]
-  then
-    echo Removing $pkg
-    if [ -e preremove/"$pkg".sh ]
-    then
-      preremove/"$pkg".sh
-      rm preremove/"$pkg".sh
-    fi
-    mapfile dt < setup/"$pkg".lst
-    for each in ${dt[*]}
-    do
-      [ -f /$each ] && rm /$each
-    done
-    for each in ${dt[*]}
-    do
-      [ -d /$each ] && rmdir --i /$each
-    done
-    rm -f setup/"$pkg".lst.gz postinstall/"$pkg".sh.done
-    awk -i inplace '$1 != ENVIRON["pkg"]' setup/installed.db
-    echo Package $pkg removed
-  fi
-  rm setup/"$pkg".lst
-  if [ $esn = 1 ]
-  then
-    warn apt-cyg cannot remove package $pkg, exiting
-    exit 1
-  fi
+        esn=$?
+        if [ $esn = 0 ]
+        then
+            echo Removing $pkg
+            if [ -e preremove/"$pkg".sh ]
+            then
+                preremove/"$pkg".sh
+                rm preremove/"$pkg".sh
+            fi
+            mapfile dt < setup/"$pkg".lst
+            for each in ${dt[*]}
+            do
+                [ -f /$each ] && rm /$each
+            done
+            for each in ${dt[*]}
+            do
+                [ -d /$each ] && rmdir --i /$each
+            done
+            rm -f setup/"$pkg".lst.gz postinstall/"$pkg".sh.done
+            awk -i inplace '$1 != ENVIRON["pkg"]' setup/installed.db
+            echo Package $pkg removed
+        fi
+        rm setup/"$pkg".lst
+        if [ $esn = 1 ]
+        then
+            warn apt-cyg cannot remove package $pkg, exiting
+            exit 1
+        fi
 
-  done
+    done
 }
 
 function apt-mirror {
-  if [ "$pks" ]
-  then
-    awk -i inplace '
+    if [ "$pks" ]
+    then
+        awk -i inplace '
     1
     /last-mirror/ {
       getline
       print "\t" pks
     }
     ' pks="$pks" /etc/setup/setup.rc
-    echo Mirror set to "$pks".
-  else
-    awk '
+        echo Mirror set to "$pks".
+    else
+        awk '
     /last-mirror/ {
       getline
       print $1
     }
     ' /etc/setup/setup.rc
-  fi
+    fi
 }
 
 function apt-cache {
-  if [ "$pks" ]
-  then
-    vas=$(cygpath -aw "$pks")
-    awk -i inplace '
+    if [ "$pks" ]
+    then
+        vas=$(cygpath -aw "$pks")
+        awk -i inplace '
     1
     /last-cache/ {
       getline
       print "\t" vas
     }
     ' vas="${vas//\\/\\\\}" /etc/setup/setup.rc
-    echo Cache set to "$vas".
-  else
-    awk '
+        echo Cache set to "$vas".
+    else
+        awk '
     /last-cache/ {
       getline
       print $1
     }
     ' /etc/setup/setup.rc
-  fi
+    fi
 }
 
-if [ -p /dev/stdin ]
-then
-  mapfile -t pks
+if [ -p /dev/stdin ] ; then
+    mapfile -t pks
 fi
 
 # process options
 until [ $# = 0 ]
 do
-  case "$1" in
+    case "$1" in
 
-    --nodeps)
-      nodeps=1
-      shift
-    ;;
+        --nodeps)
+            nodeps=1
+            shift
+            ;;
 
-    --noscripts)
-      noscripts=1
-      shift
-    ;;
+        --noscripts)
+            noscripts=1
+            shift
+            ;;
 
-    --version)
-      printf "$version"
-      exit
-    ;;
+        --version)
+            printf "$version"
+            exit
+            ;;
 
-    update)
-      command=$1
-      shift
-    ;;
+        update)
+            command=$1
+            shift
+            ;;
 
-    list | cache  | remove | depends | listall  | download | listfiles |\
-    show | mirror | search | install | category | rdepends | searchall )
-      if [[ $command ]]
-      then
-        pks+=("$1")
-      else
-        command=$1
-      fi
-      shift
-    ;;
+        list | cache  | remove | depends | listall  | download | listfiles |\
+            show | mirror | search | install | category | rdepends | searchall )
+            if [[ $command ]]
+            then
+                pks+=("$1")
+            else
+                command=$1
+            fi
+            shift
+            ;;
 
-    *)
-      pks+=("$1")
-      shift
-    ;;
+        *)
+            pks+=("$1")
+            shift
+            ;;
 
-  esac
+    esac
 done
 
 set -a
 
-if type -t apt-$command | grep -q function
-then
-  readonly arch=${HOSTTYPE/i6/x}
-  apt-$command
+if type -t apt-$command | grep -q function ; then
+    readonly arch=${HOSTTYPE/i6/x}
+    apt-$command
 else
-  printf "$usage"
+    printf "$usage"
 fi
